/** Static marketing routes included in sitemap and LLM index. */
export const MARKETING_ROUTES = [
  { path: "/", changefreq: "weekly" as const, priority: 1 },
  { path: "/features", changefreq: "monthly" as const, priority: 0.9 },
  { path: "/features/steady-send", changefreq: "monthly" as const, priority: 0.8 },
  { path: "/features/calendar", changefreq: "monthly" as const, priority: 0.8 },
  { path: "/features/expenses", changefreq: "monthly" as const, priority: 0.8 },
  { path: "/features/journal", changefreq: "monthly" as const, priority: 0.75 },
  { path: "/features/albums", changefreq: "monthly" as const, priority: 0.75 },
  { path: "/features/vault", changefreq: "monthly" as const, priority: 0.8 },
  { path: "/features/records", changefreq: "monthly" as const, priority: 0.8 },
  { path: "/pricing", changefreq: "monthly" as const, priority: 0.9 },
  { path: "/professionals", changefreq: "monthly" as const, priority: 0.9 },
  { path: "/security", changefreq: "monthly" as const, priority: 0.7 },
  { path: "/faq", changefreq: "monthly" as const, priority: 0.7 },
  { path: "/blog", changefreq: "weekly" as const, priority: 0.8 },
  { path: "/coparenting-guide", changefreq: "monthly" as const, priority: 0.75 },
  { path: "/sign-up", changefreq: "monthly" as const, priority: 0.9 },
  { path: "/contact", changefreq: "yearly" as const, priority: 0.5 },
  { path: "/privacy", changefreq: "yearly" as const, priority: 0.4 },
  { path: "/terms", changefreq: "yearly" as const, priority: 0.4 },
  { path: "/legal", changefreq: "yearly" as const, priority: 0.4 },
  { path: "/fr/conditions", changefreq: "yearly" as const, priority: 0.35 },
  { path: "/fr/confidentialite", changefreq: "yearly" as const, priority: 0.35 },
  { path: "/fr", changefreq: "monthly" as const, priority: 0.6 },
  { path: "/fr/guide-coparentalite", changefreq: "monthly" as const, priority: 0.65 },
];
